version: "3"

services: 
  app:
    container_name: react # [changable] give a suitable name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # update the port here where you want your app to run
    volumes:
      - ./:/project/app